modelcontextprotocol/go-sdk

mcp/tool.go
=> mcp: add a TODO

.github/workflows/test.yml, mcp/client_list_test.go
I noticed that some of the files weren't formatted (`go fmt` left dirty files on `main`), so I went ahead and added a `lint` CI job. We can add more linting things later if folks want, but validating formatting seemed like a nice first step.
I pushed a separate commit with `go fmt ./...` ran alone (just to make it clear what was automated changes vs manual ones).
N/A
N/A
=> feat(ci): Add check to ensure `go fmt` has been ran

mcp/protocol.go, mcp/protocol_test.go
Add an UnmarshalJSON method for that type.
Add a test.
=> mcp: fix CallToolResultFor[T] unmarshaling

mcp/logging.go, mcp/mcp_test.go, mcp/server.go
Use a verb for this method name.
=> mcp: rename LoggingMessage to Log

mcp/protocol.go
Some logically boolean fields default to true. We cannot use `bool` for these fields, because it defaults to false. So use `*bool`.
Fixes #40.
=> mcp: change default-true fields to pointers

mcp/protocol.go, mcp/shared.go
- Add some doc strings.
- Remove markdown-like notations.
=> mcp: fix some documentation

mcp/client.go, mcp/mcp_test.go, mcp/server.go, mcp/shared.go
Implement `KeepAlive` features from the design doc
Closes https://github.com/modelcontextprotocol/go-sdk/issues/24
Tested locally (unit tests).
N/A
I can send a follow-up PR adding an example with a StreamableHTTP server that uses the keepalive if that would be helpful.
=> mcp: Implement KeepAlive for client and server

README.md, internal/readme/server/server.go
Fix an example using params.Name instead of params.Arguments.Name. All credit due to @A11Might for noticing this. Sending a separate PR to keep the internal/readme source consistent.
=> internal/readme: fix server example

mcp/content_test.go, mcp/protocol.go, mcp/tool.go
- Use `any` for CallToolResult.StructuredContent.
- Change the non-generic structs into aliases for the generic ones.
=> mcp: small changes to CallTool structs

jsonschema/doc.go, jsonschema/infer.go
There's no evidence that it's needed.
Also, improve doc and error messages.
=> jsonschema: unexport ForType

mcp/content.go, mcp/content_test.go
closes #14 
This PR introduces the ResourceLink type to represent links to resources. The new type includes the following fields: `uri`, `name`, `title`, `description`, `mimeType`, `size`, and `_meta`.
This implementation conforms to the `ResourceLink` schema introduced in the [MCP schema 2025-06-18](https://github.com/modelcontextprotocol/modelcontextprotocol/blob/1cfdf1e7a8aa5065b7e3cb3e35e653df9542e0de/schema/2025-06-18/schema.json#L1826).
---
Note: `ResourceLink` extends from the `Resource` type in the MCP schema. As such, it inherits support for optional fields like `title`, `_meta`, etc. Thus, `URI`, `Name`, `Title`, `Description`, and `Size` are added to the `wireContent`
For reference, the [TypeScript SDK test suite](https://github.com/modelcontextprotocol/typescript-sdk/blob/fb4d0 …
=> mcp: add ResourceLink type

mcp/client.go, mcp/server.go, mcp/shared.go, mcp/sse.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
Support retrieving the session ID from client and server sessions.
For #65.
=> mcp: add Session.ID

mcp/content.go, mcp/content_test.go
The text field is required, but current implementation omits the text field when it is a blank string.
Some clients fail to parse the response if the text field is omitted. A blank text result is a valid MCP response.
Claude desktop error message:
```
ClaudeAiToolResultRequest.content.0.text.text: Field required
```
The solution is to return the field even when it is blank by removing `omitempty`.
=> mcp: render blank text field in TextContent instead of omitempty

mcp/content.go, mcp/content_test.go
I noticed this while working on #95. Seems Meta was accidentally skipped in the custom wire format struct.
=> mcp: ensure meta is not skipped on blob ResourceContents

go.mod, go.sum, mcp/resource.go, mcp/resource_test.go
1. Replaced the `uriTemplateToRegexp` function with the use of [yosida95/uritemplate](https://github.com/yosida95/uritemplate) to handle URI template matching as per the request.
2. Updated the relevant test cases to verify the new implementation and fixed an invalid URI template (`"file:///{}/{a}/{b}"`) that doesn't conform to RFC 6570 due to an empty `{}` expression.
3. Updated `go.mod` and `go.sum` to reflect the new dependency.
Fixes #11
=> mcp/Resource: Refactor URI Template Matching with uritemplate Library

mcp/sse.go, mcp/sse_test.go
When attempting to create an OAuth authentication on top of the SSE transport I discovered the sseClientConn was using http.DefaultClient for requests instead of the custom client provided via SSEClientTransportOptions. 
This change stores the HTTP client in the sseClientConn struct and uses it for all requests. Also adds test to verify the custom client is properly used.
=> mcp: fix sseClientConn to use custom HTTP client

jsonschema/infer.go, jsonschema/infer_test.go
Struct fields may have the "jsonschema" struct tag, which is used as the description of the property.
Fixes #47.
=> jsonschema: support "jsonschema" struct tags

jsonrpc/jsonrpc.go, mcp/client.go, mcp/server.go, mcp/shared.go, mcp/sse.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go, mcp/transport_test.go
Move the aliases to the internal/jsonrpc2 package into their own package.
Fixes #115.
=> jsonrpc: package with JSON-RPC symbols

jsonschema/LICENSE, jsonschema/README.md, jsonschema/doc.go, jsonschema/infer.go
Improve the package documentation.
Add a README and LICENSE, anticipating the relocation of this package to its own module elsewhere.
=> jsonschema: improve doc

jsonschema/doc.go
Without this, not only is the one link not valid, the entire section is considered invalid and none of the link references are used.
=> jsonschema: add missing colon to link block

examples/custom-transport/main.go, internal/jsonrpc2/messages.go, jsonrpc/jsonrpc.go
Expose `jsonrpc2.MakeID`, `jsonrpc2.EncodeMessage` and `jsonrpc2.DecodeMessage` functions to allow implementing custom `mcp.Transport`. Add an example that demonstrates a custom transport implementation.
Fixes #110
=> jsonrpc: expose encoding and decoding functions

README.md, examples/hello/main.go, internal/readme/server/server.go
Fix an example using mcp tag instead of jsonschema.
=> docs: fix the service example in the readme and examples/hello

mcp/conformance_test.go, mcp/mcp_test.go, mcp/testdata/conformance/server/prompts.txtar, mcp/testdata/conformance/server/resources.txtar, mcp/testdata/conformance/server/tools.txtar, mcp/testdata/conformance/server/version-latest.txtar, mcp/testdata/conformance/server/version-older.txtar
- Use new AddXXX API.
- Update goldens to reflect new capability logic.
Fixes #131.
=> mcp: fix conformance tests

mcp/content.go, mcp/content_test.go
This is a follow-up related to #91 (though not requiring it).
Updates `ImageContent` and `AudioContent` to use an inline wire format to ensure that required fields are not omitted during JSON marshaling, matching TypeScript schema requirements. This follows the TextContent approach.
- `ImageContent` requires `data` and `mimeType` fields.
- `AudioContent` requires `data` and `mimeType` fields.
=> mcp: don't omit required fields in ImageContent and AudioContent

jsonschema/infer.go, jsonschema/infer_test.go
Add ForLax[T], which ignores invalid types in schema inference instead of returning an error.
This allows additional customization of a schema after inference does what it can.
For example, an interface type where all the possible implementations are known can be described with "oneof".
For #136.
=> jsonschema: inference ignores invalid types

mcp/content.go
Factor out the wire type into a top-level struct.
=> mcp: dedup wire type for image and audio

mcp/event.go, mcp/event_test.go, mcp/streamable.go, mcp/streamable_test.go
Introduce an EventStore interface to store events for resumable streams.
Provide an in-memory implementation.
Still to do: connect to streaming transports.
For #10
=> mcp: add EventStore

design/design.md
In this PR, I fix two minor issues in `design.md`.
=> Fix minor issues in design.md

mcp/server.go
Use OrZero in case PingParams is nil to avoid typed nil.
Fixes: #162
=> mcp/server: fix nil PingParams in server.Ping

examples/sse/main.go
I'm making this example more useful for debugging:
- `-port` is supported
- `-host` is supported
- error handling is there.
=> mcp/examples: Make example more usable.

mcp/streamable.go
Consolidate several maps into a single struct.
Simplifies the code, for the most part.
=> mcp: add stream type

mcp/transport.go
Log internal errors from the jsonprc2 package, instead of panicking.
Fixes #175.
=> mcp: don't panic on bad JSON RPC input

mcp/server.go, mcp/server_test.go
This CL adds an option for servers to advertise support for features that have not been added yet. This includes Prompts, Tools, and Resources as these could be dynamically added after initialization.
Fixes: #135
=> mcp/server: add initial capability server option

CONTRIBUTING.md
Explain that we'll close issues or PRs after a period of inactivity.
This will reduce clutter on the issue and PR pages.
=> CONTRIBUTING.md: timeout policy

mcp/streamable.go, mcp/streamable_test.go
This CL adds the optional persistent SSE GET listener as specified in section 2.2. https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#listening-for-messages-from-the-server
This enables server initiated SSE streams.
For #10
=> mcp/streamable: add persistent SSE GET listener

design/design.md
- Correct MethodHandler type parameter to use fully qualified mcp.ServerSession
- Update parameter types to use proper mcp.Params and mcp.Result instead of any
- Ensure example code matches the actual API des
Typically, PRs should consist of a single commit, and so should generally follow
the [rules for Go commit messages](https://go.dev/wiki/CommitMessage), with the following
changes and additions:
- Markdown is allowed.
- For a pervasive change, use "all" in the title instead of a package name.
- The PR description should provide context (why this change?) and describe the changes
at a high level. Changes that are obvious from the diffs don't need to be mentioned.
=> docs: fix middleware example function signature

.github/workflows/test.yml, mcp/streamable.go
This PR contains two commits. The first adds race tests to our build matrix, inspired by #227. While the race in #227 is a _logical_ race, not a _data_ race, it is still the case that the slower timing of race tests made it more reproducible with the race detector enabled.
The second commit fixes the bug in the streamable server transport, by checking outstanding requests in the same critical section as acquiring data to write.
=> mcp: add race and 1.25 tests, fix a bug in streamable transport

jsonschema/schema.go, jsonschema/schema_test.go, mcp/testdata/conformance/server/tools.txtar
Marshal the empty schema to true, and its negation to false.
This is technically a breaking behavior change, but a properly written consumer of JSON Schema will not notice.
For #244.
Fixes #230.
=> jsonschema: marshal to bools

mcp/protocol.go, mcp/shared.go
Add unexported methods to the Params and Result interface, so that they're harder to implement outside the mcp package.
It looks like these are the only two interfaces we need to lock down: others are either intentionally open (Transport, Connection), or already closed (Session).
Fixes #263
=> mcp: lock down Params and Result

internal/jsonrpc2/conn.go, internal/jsonrpc2/frame.go, mcp/client.go, mcp/shared.go, mcp/sse.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
Add support for JSON responses in the streamable HTTP server, and simplify the streamable client. See commit messages for details.
Fixes https://github.com/modelcontextprotocol/go-sdk/issues/211
=> mcp: refactor streamable serving and support JSON responses

mcp/server.go
Make it clear that it's not needed for an HTTP server.
Fixes #273.
=> mcp: clarify Server.Run use

internal/jsonrpc2/jsonrpc2_test.go
In jsonprc2_test.go, binder.Bind starts a goroutine. That goroutine begins to run during jsonrpc2.bindConnection, and can race with the setting of conn.write in bindConnection.
This PR adds a sleep, which is a poor way to deal with the race, but the least invasive change. Better ones include running the test function after Dial returns, or adding a Connection.Ready method to detect when initialization is complete.
=> jsonrpc: paper over race in jsonrpc2 test

README.md, examples/client/listfeatures/main.go, internal/readme/client/client.go, mcp/client.go, mcp/client_list_test.go, mcp/cmd_test.go, mcp/conformance_test.go, mcp/example_middleware_test.go, mcp/logging.go, mcp/mcp_test.go, mcp/server.go, mcp/server_example_test.go, mcp/session.go, mcp/sse.go, mcp/sse_example_test.go, mcp/sse_test.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
Support stateless streamable sessions by adding a GetSessionID function to StreamableHTTPOptions. If GetSessionID returns "", the session is stateless, and no validation is performed. This is implemented by providing the session a trivial initialization state.
To implement this, some parts of #232 (distributed sessions) are copied over, since they add an API for creating an already-initialized session.
In total, the following new API is added:
- StreamableHTTPOptions.GetSessionID
- ServerSessionOptions (a new parameter to Server.Connect)
- ServerSessionState
- ClientSessionOptions (a new parameter to Client.Connect, for symmetry)
For #10
=> mcp: support stateless streamable sessions

README.md, design/design.md, examples/client/listfeatures/main.go, examples/server/hello/main.go, examples/server/memory/main.go, examples/server/sequentialthinking/main.go, internal/readme/client/client.go, internal/readme/server/server.go, mcp/cmd.go, mcp/cmd_test.go, mcp/mcp_test.go, mcp/sse.go, mcp/sse_example_test.go, mcp/sse_test.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
As described in https://github.com/modelcontextprotocol/go-sdk/issues/272, there is really no reason for transports to be closed structs with constructors, since their state must be established by a call to Connect. Making them open structs simplifies their APIs, and means that all transports can be extended in the future: we don't have to create empty Options structs just for the purpose of future compatibility.
For now, the related constructors and options structs are simply deprecated (with go:fix directives where possible). A future CL will remove them prior to the v1.0.0 release.
For https://github.com/modelcontextprotocol/go-sdk/issues/272
=> mcp: make transports open structs

README.md, design/design.md, examples/server/completion/main.go, examples/server/custom-transport/main.go, examples/server/hello/main.go, examples/server/memory/kb.go, examples/server/memory/kb_test.go, examples/server/sequentialthinking/main.go, examples/server/sequentialthinking/main_test.go, examples/server/sse/main.go, internal/readme/server/server.go, mcp/client.go, mcp/example_middleware_test.go, mcp/example_progress_test.go, mcp/mcp_test.go, mcp/resource.go, mcp/server.go, mcp/server_example_test.go, mcp/server_test.go, mcp/shared.go, mcp/shared_test.go, mcp/sse_example_test.go, mcp/streamable_test.go, mcp/tool.go, mcp/tool_test.go
Handlers and client/server methods take a single request argument combining the session and params. This slightly simplifies the signature for handlers, since there is no longer an often-ignored session argument.
But more importantly, it opens the door to adding more information in requests, such as auth info and HTTP request headers.
For #243.
=> mcp: introduce Requests

mcp/client.go, mcp/mcp_test.go, mcp/server.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
In #202, I added the checkRequest helper to validate incoming requests, and invoked it in the stremable transports to preemptively reject invalid HTTP requests, so that a jsonrpc error could be translated to an HTTP error.
However, this introduced a bug: since cancellation was handled in the jsonrpc2 layer, we never had to validate it in the mcp layer, and therefore never added methodInfo. As a result, it was reported as an invalid request in the http layer.
Add a test, and a fix. The simplest fix was to create stubs that are placeholders for cancellation.
This was discovered in the course of investigating #285.
=> mcp: fix cancellation for HTTP transport

mcp/content.go, mcp/content_nil_test.go
Check that UnmarshalJSON methods for Content don't panic on nil.
- Introduces a new test file `content_nil_test.go` which verifies that `UnmarshalJSON` methods for various `Content` types do not panic when unmarshaling onto `nil` pointers.
- Adds a `nil` check in `contentFromWire` function to guard against a `nil` `wire.Content` parameter.
- Tests cover different scenarios, including valid and invalid content types, as well as cases with empty or missing content fields.
For [modelcontextprotocol#205](https://github.com/modelcontextprotocol/go-sdk/issues/205)
=> mcp: add tests for UnmarshalJSON handling of nil Content pointers

mcp/streamable_test.go
Add a test following up on the fix for #290.
=> mcp: add a test for streamable accept headers

mcp/event.go, mcp/event_test.go, mcp/streamable.go, mcp/streamable_test.go
- Changed StreamID's to store randomly generated strings. 
- Created a defaultStreamID field on the StreamableServerTransport struct which is generated and saved on instansiation.
- Updated all tests.
Fixes #259
=> mcp: changed streamID's from int64 to random strings

mcp/server.go, mcp/server_test.go
Reorder the logic within `ServerSession.initialized` to ensure `ss.startKeepalive` is called only after the session's state is validated. 
The `startKeepalive` function is now only invoked when the session is first transitioning from `initialize` to `initialized` state.
Fixes #313
=> mcp: ensure keepalive goroutine is started exactly once

internal/jsonrpc2/conn.go, internal/jsonrpc2/jsonrpc2.go, internal/jsonrpc2/jsonrpc2_test.go, mcp/client.go, mcp/conformance_test.go, mcp/content.go, mcp/mcp_test.go, mcp/server.go, mcp/shared.go, mcp/streamable.go, mcp/streamable_test.go
Implement the concurrency model described in #26: notifications are synchronous, but calls are asynchronous (except for 'initialize'). To achieve this, implement jsonrpc2.Async(ctx) to signal asynchronous handling. This is simpler to use than returning ErrAsyncResponse and calling Respond, and since this is an internal detail we don't need to worry too much about whether it's idiomatic.
Add tests that verify both features, for both client and server.
Also:
- replace req.ID.IsValid with req.IsCall
- remove the methodHandler type as we can just use MethodHandler
Fixes #26
=> mcp: implement a concurrency model for calls

internal/jsonrpc2/conn.go, internal/jsonrpc2/wire.go, mcp/server.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
Several improvements for the stateless streamable mode, plus support for
a 'distributed' (or rather, distributable) version of the stateless
server.
- Add a 'Stateless' option to StreamableHTTPOptions and
StreamableServerTransport, which controls stateless behavior.
GetSessionID may still return a non-empty session ID.
- Audit validation of stateless mode to allow requests with a session
id. Propagate this session ID to the temporary connection.
- Peek at requests to allow 'initialize' and 'initialized' requests to go through to the
session, so that version negotiation can occur (FIXME: add tests).
Fixes #284
Fixes #10
Updates #148
=> Improvements to the stateless streamable transport

mcp/server.go, mcp/shared.go, mcp/tool.go, mcp/tool_test.go
- Fix tool error handling to properly distinguish between protocol errors and tool execution errors
- Return structured JSON-RPC errors directly for protocol-level issues
- Embed regular tool errors in CallToolResult as per MCP specification
- Improve server error responses for unknown prompts and tools
- Add comprehensive tests for both structured and regular error handling
=> improve error handling for tools and server methods

mcp/client.go, mcp/client_test.go, mcp/server.go
This CL enables the server session to see what capabilities the client has by introducing the InitializeParams() function.
This CL also adds a test to ensure ClientCapabilities is accurate.
Fixes #141
=> mcp/server: expose InitializeParams to ServerSession

mcp/shared.go, mcp/streamable.go
Add HTTP request headers to RequestExtra, so tools and other user-defined handlers can access them.
Fixes #331.
=> mcp: make request headers available to tools

mcp/protocol.go
This change adopts a clearer convention:
- any is used for fields where the structure is defined by the client or server implementer.
- an named empty struct type is the place holder type to be defined by the MCP spec in the future. 
The "Experimental" fields in "ClientCapabilities" and "ServerCapabilities" now use "map[string]any". This allows clients and servers to negotiate custom capabilities that contain complex data, rather than being restricted to a simple on/off flag.
The "Metadata" field in "CreateMessageParams" was also changed to "any" to properly serve its purpose as a flexible container for server-defined data.
=> mcp: replace type struct{} with any for user-defined fields

mcp/server.go, mcp/shared.go, mcp/streamable.go, mcp/streamable_test.go
Handle the protocol version header according to section 2.7 of the spec (and the other SDKs).
Fixes #198
=> mcp: handle the Mcp-Protocol-Version header correctly

README.md, examples/server/custom-transport/main.go, examples/server/hello/main.go, examples/server/memory/kb.go, examples/server/memory/kb_test.go, examples/server/sequentialthinking/main.go, examples/server/sequentialthinking/main_test.go, examples/server/sse/main.go, internal/readme/server/server.go, mcp/client_list_test.go, mcp/content_nil_test.go, mcp/example_middleware_test.go, mcp/features_test.go, mcp/mcp_test.go, mcp/protocol.go, mcp/protocol_test.go, mcp/server.go, mcp/server_example_test.go, mcp/shared_test.go, mcp/sse_example_test.go, mcp/streamable_test.go, mcp/tool.go, mcp/tool_test.go
=> mcp: change tool handler design

mcp/mcp_test.go, mcp/server.go
As reported in #199 and #200, the fact that we return a possibly "null" schema for pointer types breaks various clients, which expect schemas to be of type "object". This is an unfortunate footgun. For now, assume that the user wants us to treat pointers equivalently to non-pointers. If we want to change this behavior in the future, we can do so behind an option.
+ a test
Also fix the handling of nil results in the case where the output schema is non-nil: we must provide structured content in this case. (This was causing the test to fail).
Fixes #199
Fixes #200
=> mcp: treat pointers equivalently to non-pointers when deriving schema

mcp/conformance_test.go, mcp/server.go, mcp/testdata/conformance/server/tools.txtar
Some bad merging in #338 led to a bad bug in the handling of structured output for pointer output types. Add a conformance test and fix the bug.
=> mcp: fix bugs handling pointer types

mcp/client.go, mcp/client_test.go, mcp/mcp_test.go, mcp/requests.go, mcp/server.go, mcp/streamable_test.go
See related PR about ServerRequest[T].
=> mcp: remove references to ClientRequest[T] for concrete T

mcp/requests.go, mcp/server.go
This is needed so clients can modify tool schemas, and not merely to wrap ToolHandlers.
(A consequence of returning a copy of Tool instead of modifying it.)
=> mcp: export ToolFor

mcp/client.go, mcp/mcp_test.go, mcp/requests.go, mcp/server.go
This request is synthetic, and should not be observed by the user. Unexport it and rename InitializeServerRequest to just InitializeRequest.
=> mcp: unexport InitializeClientRequest

mcp/mcp_test.go, mcp/server.go, mcp/server_test.go, mcp/streamable_test.go
The spec makes it clear that input schemas must have type "object". Enforce that.
Allow "any" as an input argument type by special-casing it.
Fixes #283.
=> mcp: enforce input schema type "object"

examples/client/middleware/main.go, examples/server/middleware/main.go, mcp/mcp-repo-replace.txt
=> mcp/examples: moves middleware examples into example folder

examples/server/everything/main.go, examples/server/hello/main.go, mcp/server.go
Our 'hello' example should be as simple as possible. On the other hand, we should have an 'everything' example that exercises (almost) everything we offer.
Using the everything example, I did some final testing using the inspector. This turned up a couple rough edges related to JSON null that I addressed by preferring empty slices.
=> examples: add an everything example, and simplify hello

mcp/client.go, mcp/server.go, mcp/streamable.go, mcp/streamable_test.go, mcp/transport.go
An onClose function is passed to the ServerSession and ClientSession to help cleanup resources from the caller.
The onClose function will be executed as part of the ServerSession and ClientSession closure.
Fixes #258
=> mcp: cleanup transport after keepalive ping fails

mcp/event.go, mcp/streamable.go
This CL utilizes the event store to write outgoing messages and removes the unbounded outgoing data structure.
For #190
=> mcp/streamable: use event store to fix unbounded memory issues

examples/client/listfeatures/main.go, examples/client/loadtest/main.go
Add a loadtest client example, to help confirm performance of our streamable transport implementation.
For #190
=> examples/client: add a loadtest command

examples/server/auth-middleware/README.md, examples/server/auth-middleware/go.mod, examples/server/auth-middleware/go.sum, examples/server/auth-middleware/main.go
This commit introduces a new example demonstrating the integration of authentication middleware with an MCP server. The server supports both JWT token and API key authentication, along with scope-based access control for various MCP tools. Key features include token generation endpoints, in-memory API key storage, and a health check endpoint.
New files added:
- `main.go`: Implements the MCP server and authentication logic.
- `go.mod` and `go.sum`: Manage dependencies for the project.
- `README.md`: Provides setup instructions, available endpoints, and example usage.
This example serves as a reference for implementing secure access to MCP tools.
Fixes #330
=> feat(auth-middleware): add example MCP server with JWT and API key

README.md, internal/readme/README.src.md
Signed-off-by: Brad Hoekstra <bhoekstra@google.com>
=> cleanup: remove reference to deleted jsonschema package

examples/server/middleware/main.go
Log the result of a tool call in the middleware.
This example now fully demonstrates that receiving middleware can effectively wrap a ToolHandler. That means that one reason for ToolFor is moot: you don't need to get your hands on the returned ToolHandler in order to wrap it.
=> examples/server/middleware: log tool result

mcp/streamable.go, mcp/streamable_test.go
StreamableHTTPOptions.JsonResponse should be exported.
=> fix: export jsonResponse field

auth/auth.go, auth/auth_test.go
Add ErrOAuth error type and handling to match TypeScript SDK behavior. OAuth protocol errors now return HTTP 400 instead of 500, providing better error classification for authentication issues.
Changes
- Add ErrOAuth variable for OAuth-specific protocol errors
- Update verify function to return 400 for OAuth errors
- Add test case for OAuth error handling
Fixes compatibility with TypeScript SDK error handling patterns.
=> auth: add OAuth error handling in TokenVerifier and tests

auth/auth.go, auth/auth_test.go, examples/server/auth-middleware/main.go, mcp/streamable_test.go
The request might be needed to verify the token.
Fixes #403.
=> add HTTP Request to TokenVerifier

examples/server/auth-middleware/main.go
The additional middleware added the TokenInfo the context. RequireBearerToken already does that.
=> examples/server/auth-middleware: remove custom middleware

mcp/streamable.go, mcp/streamable_test.go
The condition sessionID == "" was not quite right for disallowing GET requests. Since we decided to differentiate "stateless" vs "sessionless" servers, we need to disallow GET requests for both.
For #393
=> mcp: correctly disallow GET requests on stateless servers

mcp/streamable.go, mcp/streamable_test.go
Flush headers immediately for the persistent hanging GET of the streamable transport; otherwise, clients may time out.
Fixes #410
=> mcp: flush headers immediately for the hanging GET

mcp/server.go, mcp/server_test.go, mcp/tool.go
toolForErr was ignoring the output schema if the output type was any.
That neglected the case where the user provided their own output schema.
Fixes #371.
=> mcp: validate user-provided output schemas

mcp/server.go, mcp/streamable_test.go, mcp/testdata/conformance/server/tools.txtar
Avoid a typed nil in structuredContent (yet another typed nil), leading to "null" on the wire.
Fixes #417
=> mcp: avoid "null" in structuredContent

examples/client/middleware/main.go, examples/server/rate-limiting/go.mod, examples/server/rate-limiting/go.sum, examples/server/rate-limiting/main.go
Update examples/server/rate-limiting to use the same replace directive strategy as the auth-middleware example, and fix the breakages.
Also remove the unneeded type parameters in examples/client/middleware.
=> examples: Update and fix outdated

mcp/server.go, mcp/streamable_test.go
For some reason, this was a regression from v0.3.1, for some of our examples. Fix it and address the existing TODO.
=> mcp: avoid "null" when tools fail to return content

mcp/event.go, mcp/event_test.go
Add a new benchmark measuring the append and purge performance of the MemoryEventStore. This benchmark revealed that the store is orders of magnitude slower than it should be due to conservative validation (hugely so: 300KB/s vs 568MB/s). Turn off this validation by default.
For #190
=> mcp: add a benchmark for the MemoryEventStore; remove validation

go.mod, go.sum, internal/testing/fake_auth_server.go
This is a fake OAuth authentication server, for use in testing.
=> internal/testing: fake auth server

mcp/server.go, mcp/server_test.go
Recently, I refactored to fix validation and default application for structured output. However, I used the wrong byte slice for the unstructured output. Fix it to use the same bytes as structured output, with a test.
Fixes #475
=> mcp: correct the JSON used for unstructured content

mcp/cmd_test.go, mcp/content_nil_test.go, mcp/mcp_test.go, mcp/protocol.go, mcp/protocol_test.go, mcp/sse_test.go, mcp/streamable_test.go
Provide a way for middleware to get the error from a tool call, demonstrating that we can add this functionality without making a breaking change.
Leave getError unexported for now; we can export it (and setError) at any time.
For #64.
=> mcp: add CallToolResult.getError

README.md, internal/readme/README.src.md, oauthex/oauthex.go
This package will hold externally visible parts of internal/oauthex.
For now, just add an alias to the ProtectedResourceMetadata struct. This lets one write MCP-compliant servers.
=> oauthex: new package for oauth extensions

docs/protocol.md, internal/docs/protocol.src.md
=> docs: add auth and security sections

mcp/client.go, mcp/mcp_test.go, mcp/resource.go, mcp/server.go, mcp/shared.go, mcp/tool_test.go
Unexport error codes that were accidentally exported. I don't think it's possible that they could be useful for users (see #535).
Fixes #535
=> mcp: unexport incidentally exported error codes

mcp/transport.go
This change keeps the logging consistent with a new line after each log whether an error or not.
Fixes #540
=> mcp: fix inconsistent logging new lines

docs/protocol.md, internal/docs/protocol.src.md, mcp/streamable_client_test.go
=> all: more minor cleanup

mcp/transport.go
We need to close stdin when the stdio transport is shut down, to unblock its read loop. However, we don't technically need to close stdout.
Fixes #548
=> mcp: don't close stdout when shutting down the stdio transport
